#!/usr/bin/env python3
"""
Analyzes C/C++ header dependencies from GNU Make dependency files (.d).

This script parses .d files, typically generated by `gcc -MMD -MP`, to build a dependency
graph. It then calculates and prints a summary of which header files are most frequently
included across the project. This is useful for identifying headers that, if refactored,
could significantly reduce build times.

To generate the required .d files, your Makefile's compilation rule should
include the `-MMD` and `-MP` flags. For example:

    $(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

Usage:
    python3 analyze_dependencies.py [build_directory]

Arguments:
    build_directory: The path to the directory containing the .d files.
                     Defaults to 'build/'.
"""
import argparse
import os
import sys
from collections import defaultdict


def analyze_dependencies(build_dir: str):
	"""
    Parses .d files in the build directory to create a dependency graph.

    Args:
        build_dir: The path to the build directory.

    Returns:
        A tuple containing two dictionaries:
        - dependents: A dictionary mapping each header to a list of files that depend on it.
        - dependencies: A dictionary mapping each file to a list of headers it depends on.
    """
	dependents = defaultdict(list)
	dependencies = defaultdict(list)

	if not os.path.isdir(build_dir):
		print(f"Error: Build directory not found at '{build_dir}'", file=sys.stderr)
		sys.exit(1)

	for root, _, files in os.walk(build_dir):
		for file in files:
			if file.endswith('.d'):
				filepath = os.path.join(root, file)
				with open(filepath, 'r') as f:
					# Join lines, handling backslash-escaped newlines
					content = f.read().replace(' \\\n', ' ')
					parts = content.split(': ')
					if len(parts) == 2:
						# The first part is the target object file (e.g., 'build/main.o')
						target = parts[0]
						# The second part is the list of dependencies
						deps = parts[1].split()
						dependencies[target] = deps
						for dep in deps:
							if dep.endswith('.h') or dep.endswith('.hpp'):
								dependents[dep].append(target)

	return dependents, dependencies


def print_dependency_summary(dependents: dict):
	"""
    Prints a summary of the dependency analysis.

    Args:
        dependents: A dictionary mapping each header to a list of files that depend on it.
    """
	if not dependents:
		print("No dependencies found. Did you generate the .d files?")
		return

	print("Top 10 most included headers:")
	sorted_dependents = sorted(dependents.items(), key=lambda item: len(item[1]), reverse=True)
	for i, (header, files) in enumerate(sorted_dependents[:10]):
		print(f"{i + 1}. {header}: included by {len(files)} files")

	print("\nFull dependency report:")
	for header, files in sorted_dependents:
		print(f"\n{header} is included by:")
		for file in sorted(files):
			print(f"  - {file}")


def main():
	"""Main entry point for the script."""
	parser = argparse.ArgumentParser(description="Analyze C/C++ header dependencies from .d files."
	)
	parser.add_argument(
		"build_directory",
		nargs='?',
		default='build',
		help="Path to the directory containing .d files (default: 'build')"
	)
	args = parser.parse_args()

	dependents, _ = analyze_dependencies(args.build_directory)
	print_dependency_summary(dependents)


if __name__ == "__main__":
	main()
