# Project configuration
site_name: Squirt Water Turret Documentation
site_url: https://ricecake.github.io/squirtWaterTurret/
repo_url: https://github.com/ricecake/squirtWaterTurret
docs_dir: documentation

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Navigation
nav:
  - 'Home': 'index.md'
  - 'Core Concepts': 'Core_Concepts.md'
  - 'Architecture': 'Architecture.md'
  - 'Firmware':
    - 'Firmware Classes': 'Firmware_Classes.md'
    - 'Communication Protocol': 'Communication_Protocol.md'
  - 'Computer Vision': 'CV_System.md'
  - 'Algorithms and Math': 'Algorithms_and_Math.md'
  - Code Reference: 'squirt-water-turret/'

# Plugins
plugins:
  - search
  - literate-nav:
  - mkdoxy:
      projects:
        'squirt-water-turret':
          src-dirs: '.'
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: 'Squirt Water Turret'
            INPUT: '.'
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True
            EXCLUDE: './fpm ./tests ./documentation ./gh-pages ./site ./git ./vscode ./external LD2450.cpp LD2450.h'
            GENERATE_LATEX: False
            GENERATE_HTML: False
            GENERATE_XML: True
            XML_OUTPUT: 'xml'
