baseURL = "https://ricecake.github.io/squirtWaterTurret/"
languageCode = "en-us"
title = "Squirt Water Turret"
theme = "geekdoc"

pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  geekdocLogo = "logo.png"
  geekdocRepo = "https://github.com/ricecake/squirtWaterTurret"
  geekdocBreadcrumb = true
